# Generated by Django 4.2.9 on 2026-05-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
        ("interviews", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewsession",
            name="questions",
            field=models.ManyToManyField(
                blank=True, related_name="sessions", to="questions.question"
            ),
        ),
    ]
